baseurl = "https://github.com/jacques28/blog-app"
builddrafts = false
canonifyurls = false
languageCode = "en-US"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
author = "Jack "
title = "Jack's Blog"
theme = "hugo-goa"
googleAnalytics = "XYZ"
enableRobotsTXT = true
[params]
author = "Jack "
intro = "Software Engineer"
description = "Now @coming soon. Previously @Soptirec @Stociattitude.<br/> \"Want to know more check about me.\""
authorimage = "logo.jpg"
dateformat = "Jan 2, 2006"
## Site Meta Settings
[params.meta]
description = "Simple minimalist blog"
keywords = "minimalist,blog,developer"
## Social Accounts
[params.social]
github = " "
instagram = " "
twitter = " "
email = "devjacques28i@gmail.com"
## Extras
[params.extra]
 content= "Built by Jack"
## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "posts"
    identifier = "posts"
    weight = 300
    url = "/posts/"